[package]
name = "poly_battle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
rand = "*"
image = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"